pipeline:
  build:
    group: build
    image: plugins/docker
    repo: cctech/ruby
    dockerfile: Dockerfile
    tags:
      - latest-ci
      - ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
